# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meet_date',
            field=models.DateField(default=datetime.date(2016, 8, 2)),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='meet_time',
            field=models.TimeField(default=b'12:56:09'),
        ),
    ]
