# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0002_auto_20160802_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='meet_time',
            field=models.TimeField(default=b'13:01:55'),
        ),
    ]
